// <auto-generated />
using System;
using CQELight.DAL.EFCore.Integration.Tests;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CQELight.DAL.EFCore.Integration.Tests.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("CQELight.DAL.EFCore.Integration.Tests.AzureLocation", b =>
                {
                    b.Property<string>("Country");

                    b.Property<string>("DataCenter");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Deleted")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeleteDate")
                        .HasDefaultValue(null);

                    b.Property<DateTime>("EditDate")
                        .HasColumnName("EditDate");

                    b.HasKey("Country", "DataCenter");

                    b.ToTable("AzureLocation");
                });

            modelBuilder.Entity("CQELight.DAL.EFCore.Integration.Tests.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Comment_Id");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Deleted")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeleteDate")
                        .HasDefaultValue(null);

                    b.Property<DateTime>("EditDate")
                        .HasColumnName("EditDate");

                    b.Property<Guid>("Owner_Id")
                        .HasColumnName("User_Id");

                    b.Property<Guid>("Post_Id")
                        .HasColumnName("Post_Id");

                    b.Property<string>("Value")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("Owner_Id");

                    b.HasIndex("Post_Id", "Owner_Id", "Value");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("CQELight.DAL.EFCore.Integration.Tests.ComposedKeyEntity", b =>
                {
                    b.Property<string>("FirstPart");

                    b.Property<string>("SecondPart");

                    b.HasKey("FirstPart", "SecondPart");

                    b.ToTable("ComposedKeyEntity");
                });

            modelBuilder.Entity("CQELight.DAL.EFCore.Integration.Tests.Hyperlink", b =>
                {
                    b.Property<string>("Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Hyperlink")
                        .HasMaxLength(1024);

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Deleted")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeleteDate")
                        .HasDefaultValue(null);

                    b.Property<DateTime>("EditDate")
                        .HasColumnName("EditDate");

                    b.Property<Guid>("WebSite_Id")
                        .HasColumnName("WebSite_Id");

                    b.HasKey("Value");

                    b.HasIndex("WebSite_Id");

                    b.ToTable("Hyperlinks");
                });

            modelBuilder.Entity("CQELight.DAL.EFCore.Integration.Tests.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Post_Id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnName("Content")
                        .HasMaxLength(65536);

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Deleted")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeleteDate")
                        .HasDefaultValue(null);

                    b.Property<DateTime>("EditDate")
                        .HasColumnName("EditDate");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnName("PublicationDate");

                    b.Property<bool>("Published")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Published")
                        .HasDefaultValue(true);

                    b.Property<string>("QuickUrl")
                        .HasColumnName("ShortAccess")
                        .HasMaxLength(2048);

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Version")
                        .HasDefaultValue(1);

                    b.Property<Guid>("WebSiteId")
                        .HasColumnName("WebSite_Id");

                    b.Property<Guid?>("Writer_Id")
                        .HasColumnName("User_Id");

                    b.HasKey("Id");

                    b.HasIndex("QuickUrl")
                        .IsUnique();

                    b.HasIndex("WebSiteId");

                    b.HasIndex("Writer_Id");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("CQELight.DAL.EFCore.Integration.Tests.PostTag", b =>
                {
                    b.Property<Guid>("Post_Id")
                        .HasColumnName("Post_Id");

                    b.Property<Guid>("Tag_Id")
                        .HasColumnName("Tag_Id");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Deleted")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeleteDate")
                        .HasDefaultValue(null);

                    b.Property<DateTime>("EditDate")
                        .HasColumnName("EditDate");

                    b.HasKey("Post_Id", "Tag_Id");

                    b.HasIndex("Tag_Id");

                    b.ToTable("PostTag");
                });

            modelBuilder.Entity("CQELight.DAL.EFCore.Integration.Tests.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Tag_Id");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Deleted")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeleteDate")
                        .HasDefaultValue(null);

                    b.Property<DateTime>("EditDate")
                        .HasColumnName("EditDate");

                    b.Property<string>("Value")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("CQELight.DAL.EFCore.Integration.Tests.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("User_Id");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Deleted")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeleteDate")
                        .HasDefaultValue(null);

                    b.Property<DateTime>("EditDate")
                        .HasColumnName("EditDate");

                    b.Property<string>("LastName")
                        .HasColumnName("LastName");

                    b.Property<string>("Name")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CQELight.DAL.EFCore.Integration.Tests.WebSite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("WebSite_Id");

                    b.Property<string>("AzureCountry")
                        .HasColumnName("AzureCountry");

                    b.Property<string>("AzureDataCenter")
                        .HasColumnName("AzureDataCenter");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Deleted")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DeleteDate")
                        .HasDefaultValue(null);

                    b.Property<DateTime>("EditDate")
                        .HasColumnName("EditDate");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnName("URL");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("AzureCountry", "AzureDataCenter");

                    b.ToTable("WebSite");
                });

            modelBuilder.Entity("CQELight.DAL.EFCore.Integration.Tests.Word", b =>
                {
                    b.Property<string>("WordValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Word_Id");

                    b.Property<Guid>("Tag_Id")
                        .HasColumnName("Tag_Id");

                    b.HasKey("WordValue");

                    b.HasIndex("Tag_Id");

                    b.ToTable("Word");
                });

            modelBuilder.Entity("CQELight.DAL.EFCore.Integration.Tests.Comment", b =>
                {
                    b.HasOne("CQELight.DAL.EFCore.Integration.Tests.User", "Owner")
                        .WithMany("Comments")
                        .HasForeignKey("Owner_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CQELight.DAL.EFCore.Integration.Tests.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("Post_Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CQELight.DAL.EFCore.Integration.Tests.Hyperlink", b =>
                {
                    b.HasOne("CQELight.DAL.EFCore.Integration.Tests.WebSite", "WebSite")
                        .WithMany("HyperLinks")
                        .HasForeignKey("WebSite_Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CQELight.DAL.EFCore.Integration.Tests.Post", b =>
                {
                    b.HasOne("CQELight.DAL.EFCore.Integration.Tests.WebSite", "WebSite")
                        .WithMany("Posts")
                        .HasForeignKey("WebSiteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CQELight.DAL.EFCore.Integration.Tests.User", "Writer")
                        .WithMany("Posts")
                        .HasForeignKey("Writer_Id")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CQELight.DAL.EFCore.Integration.Tests.PostTag", b =>
                {
                    b.HasOne("CQELight.DAL.EFCore.Integration.Tests.Post", "Post")
                        .WithMany("Tags")
                        .HasForeignKey("Post_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CQELight.DAL.EFCore.Integration.Tests.Tag", "Tag")
                        .WithMany("Posts")
                        .HasForeignKey("Tag_Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CQELight.DAL.EFCore.Integration.Tests.WebSite", b =>
                {
                    b.HasOne("CQELight.DAL.EFCore.Integration.Tests.AzureLocation", "AzureLocation")
                        .WithMany()
                        .HasForeignKey("AzureCountry", "AzureDataCenter")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CQELight.DAL.EFCore.Integration.Tests.Word", b =>
                {
                    b.HasOne("CQELight.DAL.EFCore.Integration.Tests.Tag", "Tag")
                        .WithMany("Words")
                        .HasForeignKey("Tag_Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
